apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: surveys
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: db-credentials
  data:
  - secretKey: host
    remoteRef:
      key: topsurvey-dev-db-credentials
      property: host
  - secretKey: user
    remoteRef:
      key: topsurvey-dev-db-credentials
      property: user
  - secretKey: password
    remoteRef:
      key: topsurvey-dev-db-credentials
      property: password
  - secretKey: database
    remoteRef:
      key: topsurvey-dev-db-credentials
      property: database